name: simple-linked-list
version: 0.1.0.3

dependencies:
  - base

library:
  exposed-modules: LinkedList
  source-dirs: src
  ghc-options: -Wall
  default-extensions:
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DeriveLift
    - DerivingStrategies
    - GeneralizedNewtypeDeriving
    - OverloadedStrings
    - OverloadedLabels
    - ExistentialQuantification
    - StandaloneDeriving
    - ScopedTypeVariables
    - UnicodeSyntax
    - BinaryLiterals
    - NumDecimals
    - ConstraintKinds
    - RankNTypes
    - TypeFamilies
    - TypeInType
    - PolyKinds
    - DataKinds
    - KindSignatures
    - TypeOperators
    - TypeApplications
    - GADTs
    - NamedFieldPuns
    - InstanceSigs
    - TypeSynonymInstances
    - MultiParamTypeClasses
    - FunctionalDependencies
    - ConstrainedClassMethods
    - InstanceSigs
    - FlexibleInstances
    - FlexibleContexts
    - BangPatterns
    - ViewPatterns
    - PatternGuards
    - MultiWayIf
    - EmptyCase
    - LambdaCase
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - simple-linked-list
      - hspec
      - QuickCheck
