name: collatz-conjecture
version: 1.2.1.4

dependencies:
  - base

library:
  exposed-modules: CollatzConjecture
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - collatz-conjecture
      - hspec

default-extensions: DeriveFoldable
  , DeriveFunctor
  , DeriveGeneric
  , DeriveTraversable
  , DeriveLift
  , DeriveAnyClass
  , DerivingStrategies
  , GeneralizedNewtypeDeriving
  , OverloadedStrings
  , OverloadedLabels
  , ExistentialQuantification
  , StandaloneDeriving
  , ScopedTypeVariables
  , UnicodeSyntax
  , BinaryLiterals
  , NumDecimals
  , ConstraintKinds
  , RankNTypes
  , TypeFamilies
  , TypeInType
  , PolyKinds
  , DataKinds
  , KindSignatures
  , TypeOperators
  , TypeApplications
  , GADTs
  , NamedFieldPuns
  , InstanceSigs
  , PartialTypeSignatures
  , TypeSynonymInstances
  , MultiParamTypeClasses
  , FunctionalDependencies
  , ConstrainedClassMethods
  , InstanceSigs
  , FlexibleInstances
  , FlexibleContexts
  , BangPatterns
  , ViewPatterns
  , PatternGuards
  , MultiWayIf
  , EmptyCase
  , LambdaCase
